spring:
  application:
    name: eureka-server
server:
    port: 8888
eureka:
    client:
      service-url:
        register-with-eureka: false
        fetch-registry: false
        defaultZone: http://localhost:8888/eureka/